### PR TITLE
typos correction & new word

### PR DESCRIPTION
**Pull request by deltaplanoo**
New dictionary word: Oro
Few typos corrected

### CODE REVIEW

**Review by Jacopown — CHANGES_REQUESTED** [review]
Boca de lobo was right, the sentence is in Spanish so "del" doesn't exists, they use "de"

**Comment by deltaplanoo** [comment]
Gella asked me to add "_sarà i'bene_" but I've never heard him use it, or at least it's not one of his frequent expression. 
I think that's all! 👍

**Comment by Jacopown** [comment]
Perfect, change what I told u before and I'll merge

**Comment by deltaplanoo** [comment]
ok, this should be good

**Pull request merged**
